### PR TITLE
Hammerer hase a skin now

### PR DESCRIPTION
**Pull request by Eddyskingdom**
i change the name form EXECUTIONER to HAMMERER

### CODE REVIEW

**Comment by claireanlage** [comment]
Looks good. Thanks.

**Comment by Eddyskingdom** [comment]
@claireanlage thank you for merging it I have been waiting for a while for somebody to do it.

**Comment by claireanlage** [comment]
Thank you for the pull request. I went ahead and checked the other graphic sets and fixed it where it was necessary.

**Comment by Eddyskingdom** [comment]
Is there a way to contact you if I make more pull requests?

**Comment by claireanlage** [comment]
You can PM me on the bay12 forum (CLA) or write me a message on github. I hope I would get a email notification at least in that case. Jecowa used to be active in maintaining the DFGraphics repo so I never checked.

**Comment by Eddyskingdom** [comment]
hey CLA i want to work to improve Phoebus Graphics and i want to contact you easier so could you like send me a your e-mail so i could ask you some thing i don't understand in the graphics like why is there aikoncwd file with new_(race).png that i havent seen in the base game?

**Comment by claireanlage** [comment]
I'd prefer to use private messages on the bay12 forum. You're username on the forum is the same, right? The graphics you're referring to seem to be for the new professions that have been added in 0.44.01 (prophet, pilgrim, etc).

See also:
https://github.com/DFgraphics/Phoebus/blob/master/raw/graphics/graphics_aikoncwd_professions.txt
I don't know why you don't see them in your game. Are you sure you found a person with that profession?

**Comment by Eddyskingdom** [comment]
Yes my username is the same but if you have a discord it be much easier for me atleast also now i understand the new professions i looked around for it

**Pull request merged**
